### ISSUE TITLE
Implement insertion sort

### ISSUE THREAD

**Issue by ricardoholmes** [ricardoholmes/SortAlgorithmVisualiser#2]
Fairly simple to do, just make a class that extends Sorter and implement the getName() and sort() functions

**Comment by ishrivasayush** [comment]
I would like to work on this issue. Please assign it to me

**Comment by ricardoholmes** [comment]
Alright

**Comment by shivam0277** [comment]
please assign me this issue . i would love to work on it .

**Comment by ricardoholmes** [comment]
@ishrivasayush are you working on this?
